# Generated by Django 3.2.6 on 2021-08-31 10:17

from django.db import migrations, models
import geolocation_fields.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='points',
            field=geolocation_fields.models.fields.PointField(blank=True, null=True, verbose_name='Point'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/default.png', null=True, upload_to=None),
        ),
    ]
