# Generated by Django 3.2.6 on 2021-08-31 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, default='media/default.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='thumb',
            field=models.ImageField(blank=True, default='media/default.png', null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='image',
            field=models.ImageField(blank=True, default='media/default.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='project_gallery',
            field=models.ForeignKey(blank=True, default='media/default.png', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.image'),
        ),
    ]
