# Generated by Django 3.2.6 on 2021-09-01 06:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210831_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposals',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
