# Generated by Django 3.2.6 on 2021-09-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_proposals_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='create',
            field=models.DateTimeField(auto_now=True, max_length=100, null=True),
        ),
    ]
