# Generated by Django 3.2.6 on 2021-08-31 10:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_vendors_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='city',
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='item_quantity',
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='location',
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='package_type',
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='previous_work_Description',
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='prodcut_amount',
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='ratings',
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='reviews',
        ),
        migrations.CreateModel(
            name='VendorsReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vendors')),
            ],
        ),
    ]
