# Generated by Django 3.2.6 on 2021-09-02 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packages_type', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.TimeField()),
                ('amount', models.PositiveIntegerField(blank=True, default=0)),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vendors')),
            ],
        ),
        migrations.CreateModel(
            name='CreateCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cart')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
        ),
    ]
