# Generated by Django 3.2.6 on 2021-08-31 10:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210831_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='services',
            name='review',
        ),
        migrations.CreateModel(
            name='ServicesReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.services')),
            ],
        ),
    ]
