# Generated by Django 3.2.6 on 2021-09-02 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210902_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(blank=True, default='media/default.png', null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='categories',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vendors'),
        ),
    ]
