# Generated by Django 3.2.6 on 2021-09-02 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210902_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='vendor',
        ),
        migrations.AddField(
            model_name='vendors',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.categories'),
        ),
    ]
