# Generated by Django 3.2.6 on 2021-09-03 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210902_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='image',
            new_name='event_image',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='name',
            new_name='event_location',
        ),
        migrations.RemoveField(
            model_name='createcart',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='create',
        ),
        migrations.RemoveField(
            model_name='order',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='event_location',
        ),
        migrations.RemoveField(
            model_name='order',
            name='event_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='event_title',
        ),
        migrations.RemoveField(
            model_name='order',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_datetime',
        ),
        migrations.RemoveField(
            model_name='order',
            name='taxes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='vendor_id',
        ),
        migrations.RemoveField(
            model_name='services',
            name='vendor_id',
        ),
        migrations.AddField(
            model_name='createcart',
            name='Packages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.packages'),
        ),
        migrations.AddField(
            model_name='createcart',
            name='Packages_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='createcart',
            name='Product_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='events',
            name='Vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vendors'),
        ),
        migrations.AddField(
            model_name='events',
            name='event_date',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='event_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='event_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='event_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vendors'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_create',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='vendors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vendors'),
        ),
        migrations.AddField(
            model_name='services',
            name='vendors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vendors'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_createdDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_createdTime',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='duration',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product_type', models.CharField(max_length=100, null=True)),
                ('prodcut_amount', models.PositiveIntegerField(default=0)),
                ('vendors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vendors')),
            ],
        ),
        migrations.AddField(
            model_name='createcart',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
    ]
