# Generated by Django 3.2.6 on 2021-09-06 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210906_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createcart',
            name='Packages_quantity',
        ),
        migrations.RemoveField(
            model_name='events',
            name='Vendor',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Vendor',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='amount',
        ),
        migrations.AddField(
            model_name='createcart',
            name='prodcut_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='Packages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.packages'),
        ),
        migrations.AddField(
            model_name='order',
            name='Cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.createcart'),
        ),
    ]
