# Generated by Django 3.2.6 on 2021-09-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210909_0609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodcut_amount',
            new_name='product_amount',
        ),
    ]
