# Generated by Django 3.2.6 on 2021-09-16 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_prodcut_amount_product_product_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='prodcut_amount',
            new_name='product_amount',
        ),
    ]
