# Generated by Django 3.2.6 on 2021-09-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_prodcut_amount_cartitem_product_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendors',
            old_name='is_favorite',
            new_name='is_favourite',
        ),
    ]
